/**
 * @file libRfid.h
 * @brief Contains functions and definitions for managing RFID reader.
 * 
 * Contains functions and definitions for managing RFID reader.
 */

#ifndef LIBRFID_H_DEFINITION
#define LIBRFID_H_DEFINITION

#include <Arduino.h>
#include <SPI.h>
#include <MFRC522.h>

#include "mainAppDefinitions.h"
#include "utils.h"

#define RFID_CS_PIN 5
// #define RFID_RST_PIN 000

extern MFRC522 mfrc522;

// TODO this was generated by ChatGPT rewrite it please!!!
// Also .cpp file...

/**
 * @brief Scans for a card.
 * @return true if a card is found, false otherwise.
 */
// bool isCardPresent();

/**
 * @brief Reads the RFID card's unique ID.
 * @param uidBuffer A buffer to store the card's UID (length should be 10).
 * @return true if the UID was successfully read, false otherwise.
 */
// bool readCardUid(char* uidBuffer);

/**
 * @brief Compares the scanned card UID with a stored UID.
 * @param scannedUid The UID of the scanned card.
 * @param storedUid The stored UID to compare against.
 * @return true if the UIDs match, false otherwise.
 */
// bool compareUid(const char* scannedUid, const char* storedUid);

/**
 * @brief Invalidates a scanned card (e.g., triggers alarm).
 * @param uid The UID of the card to invalidate.
 * @return true if invalidation was successful, false otherwise.
 */
// bool invalidateCard(const char* uid);

#endif